import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import '@ant-design/v5-patch-for-react-19';

import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	const session = await auth();
  return (
	<SessionProvider session={session}>
		<html lang="en">
			<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AntdRegistry >
					<ConfigProvider
						theme={{
						token: {
							colorPrimary: '#63b03e',
							borderRadius: 2,
							colorTextBase: '#242424',
							fontFamily: 'inherit',
							fontWeightStrong: 600,
							fontSize: 16,
							// lineWidth: 600,
							colorBorder: '#8b8b8b',
							colorTextPlaceholder: '#afafaf',
							colorLink: '#63b03e',
							colorFillTertiary: '#a3a2a2', // Цвет слайдера
						},
						components: {
							Divider: {
							orientationMargin: 0,
							textPaddingInline: 1,
							},
							Slider: {
							railBg: '#8b8b8b',
							trackHoverBg: '#63b03e',
							trackBg: '#63b03e',
							},
							Checkbox: {
								fontSize: 14,
							}
						},
						}}
					>
						{children}
					</ConfigProvider>
				</AntdRegistry>
			</body>
		</html>
    </SessionProvider>
  );
}
